---
# Camera Configuration

- name: Enable camera interface
  ansible.builtin.lineinfile:
    path: "{{ rpi_boot_config_file }}"
    regexp: "^#?start_x="
    line: "start_x=1"
    state: present
  when: rpi_camera_enable | bool

- name: Disable camera LED
  ansible.builtin.lineinfile:
    path: "{{ rpi_boot_config_file }}"
    regexp: "^#?disable_camera_led="
    line: "disable_camera_led={{ 1 if rpi_camera_disable_led | bool else 0 }}"
    state: "{{ 'present' if rpi_camera_disable_led | bool else 'absent' }}"
  when: rpi_camera_enable | bool
