---
- name: Copy bash scripts
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ netdata_scripts_dir }}/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: "{{ netdata_script_mode }}"
    owner: root
    group: root
  loop:
    - memory_trigger.sh.j2
  when: netdata_memory_trigger_enabled | bool
  notify: Restart netdata
  tags: netdata
