---
- name: Copy MySQL alarm configurations
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ netdata_health_dir }}/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: "{{ netdata_config_file_mode }}"
    owner: root
    group: root
  loop:
    - mysql_slow_queries.conf.j2
    - mysql_high_connection_rate.conf.j2
    - mysql_high_aborted_connections.conf.j2
    - mysql_low_available_connections.conf.j2
    - mysql_table_lock_contention.conf.j2
    - mysql_high_read_write_ratio.conf.j2
    - mysql_temp_tables_on_disk.conf.j2
    - mysql_innodb_buffer_usage.conf.j2
    - mysql_replication_lag.conf.j2
    - mysql_innodb_deadlocks.conf.j2
  notify: Restart netdata
  tags: netdata
