---
- name: Copy ZFS alarm configurations
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ netdata_health_dir }}/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: "{{ netdata_config_file_mode }}"
    owner: root
    group: root
  loop:
    - zfs-arc-size-ARC.conf.j2
    - zfs_arc_miss_rate.conf.j2
    - zfs_pool_capacity.conf.j2
    - zfs_disk_errors.conf.j2
    - zfs_pool_fragmentation.conf.j2
  notify: Restart netdata
  tags: netdata
