---

- name: Setup /etc/hosts with node ip
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^[0-9\.]+[ \t]+(.*{{ ansible_hostname }}.*)'
    line: '{{ proxmox_ve__cluster_ip }} \1'
    backrefs: yes
    state: present
    backup: true
