---
galaxy_info:
  author: Almir Zohorovic
  description: This ansible role will Install virtualbox on targets
  license: GPL-3.0-or-later
  min_ansible_version: "2.9"
  
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  
  galaxy_tags:
    - applications
    - virtualization

dependencies: []

