
bash_aliases:
  - "alias gs='git status'"
  - "alias ll='ls -lah'"
  - "alias neofetch='fastfetch'"
  - 'export PS1="\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\$ "'
  - "alias cls='clear && ls'"
  - "alias gts='gnome-text-editor'"