# Flatpak ---------------------------------------------------------
flatpak_repo: https://flathub.org/repo/flathub.flatpakrepo

flatpak_packages:
  # ğŸ› ï¸ Utilities
  - com.github.qarmin.czkawka
  - org.fedoraproject.MediaWriter
  - org.torproject.torbrowser-launcher
  - com.github.tchx84.Flatseal
  - net.nokyan.Resources

  # ğŸ§ Multimedia
  - net.codeindustry.MasterPDFEditor
  - org.clementine_player.Clementine
  - org.darktable.Darktable
  - com.github.weclaw1.ImageRoll
  - org.gnome.gitlab.YaLTeR.VideoTrimmer
  - de.haeckerfelix.Shortwave
  - io.github._0xzer0x.qurancompanion
  - com.spotify.Client

  # ğŸ—¨ï¸ Communication / Messaging
  - com.slack.Slack
  - org.signal.Signal
  - org.telegram.desktop

  # ğŸ‘¨â€ğŸ’» Development Tools
  - io.dbeaver.DBeaverCommunity
  - com.usebottles.bottles
  - org.freecad.FreeCAD

  # ğŸ—ºï¸ Mapping / Utilities / Misc
  - app.organicmaps.desktop
  - io.gitlab.theevilskeleton.Upscaler
  - com.rtosta.zapzap
  - io.github.flattool.Warehouse
  - org.kiwix.desktop
