
- name: Set GNOME desktop background settings using dconf | Background
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/color-shading-type"
    value: "'solid'"

- name: Set picture options for GNOME desktop background | Background
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: Copy wallpaper to home directory | Background
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "{{ wallpaper_src }}"
    dest: "{{ wallpaper_dest }}/wallpaper.png"
    owner: almir
    group: almir
    mode: '0644'
  when: wallpaper is defined and wallpaper == true

- name: Set picture URI for GNOME desktop background | Backgroundv
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/gnome/vnc-l.png'"

- name: Set dark picture URI for GNOME desktop background | Background
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/gnome/vnc-d.png'"

- name: Set primary color for GNOME desktop background | Background
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/primary-color"
    value: "'#77767B'"

- name: Set secondary color for GNOME desktop background | Background
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/secondary-color"
    value: "'#000000'"
