---

- name: Get system architecture for Flatpak refs
  ansible.builtin.set_fact:
    flatpak_arch: "{{ 'x86_64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
  when: use_flatpak

- name: Create user directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  loop:
    - "{{ scripts_dir }}"
    - "{{ data_dir }}"
  become: yes

- name: Include Package Manager Setup
  ansible.builtin.include_tasks: package_manager.yml

- name: Include Geospatial Software Installation
  ansible.builtin.include_tasks: software.yml
  when: install_geospatial_software

- name: Include Map Data
  ansible.builtin.include_tasks: maps.yml
  when: install_map_data

- name: Include GPS Hardware Support
  ansible.builtin.include_tasks: gps.yml
  when: install_gps_support

