---
# =============================================================================
# NUT Role Metadata
# =============================================================================

dependencies: []

collections:
  - ansible.builtin
  - ansible.posix
  - community.general
