---
- name: Configure common kernel parameters for MySQL
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: false
  loop: "{{ mysql_common_sysctl_settings }}"
  notify: Reload sysctl
  tags: [mysql_tuning, sysctl]

- name: Include OS-specific MySQL tuning tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family in ['RedHat', 'Debian']
  tags: [mysql_tuning]
