
- name: Check if NVIDIA GPU is detected
  command: lspci | grep -i nvidia
  register: nvidia_gpu_check
  failed_when: false
  changed_when: false

- name: Install NVIDIA-related packages
  ansible.builtin.package:
    name: "{{ nvidia_packages }}"
    state: present
  when: nvidia_gpu_check.stdout != ""