---
# Handlers for Kiwix role

- name: restart kiwix service
  ansible.builtin.systemd:
    name: kiwix-serve
    state: restarted
  when: kiwix_install_method == 'package'

- name: restart docker container
  community.docker.docker_container:
    name: "{{ kiwix_docker_container_name }}"
    state: restarted
  when: kiwix_install_method == 'docker'

